# Generated by Django 5.2.1 on 2025-07-08 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2025, 7, 8, 0, 43, 5, 786268, tzinfo=datetime.timezone.utc)),
        ),
    ]
