# Generated by Django 5.2.1 on 2025-07-31 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_delete_user_movie_length_movie_synopsis_movie_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 0, 2, 3, 233100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2025, 7, 31, 0, 2, 3, 233100, tzinfo=datetime.timezone.utc)),
        ),
    ]
