# Generated by Django 5.2.1 on 2025-07-31 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_movie_start_time_movie_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2025, 7, 31, 0, 34, 42, 645862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 0, 34, 42, 644913, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.CharField(default='videos/vvideo.mp4', max_length=200),
        ),
    ]
