# Generated by Django 5.2.1 on 2025-08-05 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_comment_created_date_alter_movie_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2025, 8, 5, 0, 17, 42, 222492, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2025, 8, 4, 21, 19)),
        ),
    ]
