# Generated by Django 5.2.1 on 2025-08-05 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_comment_created_date_alter_movie_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2025, 8, 5, 1, 10, 34, 805208, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 1, 10, 34, 802155, tzinfo=datetime.timezone.utc)),
        ),
    ]
