# Generated by Django 5.2.1 on 2025-08-06 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_comment_created_date_alter_movie_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 0, 29, 20, 216080, tzinfo=datetime.timezone.utc)),
        ),
    ]
