# Generated by Django 5.2.1 on 2025-08-12 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_alter_movie_start_time_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 0, 51, 34, 94513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
