# Generated by Django 5.2.1 on 2025-08-20 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_movie_start_time_rating_unique_user_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 0, 54, 36, 663817, tzinfo=datetime.timezone.utc)),
        ),
    ]
