# Generated by Django 5.2.1 on 2025-08-22 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_alter_movie_start_time_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 0, 11, 1, 142436, tzinfo=datetime.timezone.utc)),
        ),
    ]
