# Generated by Django 5.2.1 on 2025-08-26 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_alter_movie_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/avatar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 26, 0, 18, 16, 822739, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
