# Generated by Django 5.2.1 on 2025-08-27 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_profile_avatar_profile_bio_alter_movie_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_url',
        ),
    ]
